export const ComponentDefaultProps = {
  HEADING: {
    style: {
      backgroundColor: { r: 255, g: 255, b: 255, a: 1 },
      color: { r: 0, g: 0, b: 0, a: 1 },
      fontSize: { value: "32", unit: "px" },
      fontWeight: "bold",
      letterSpacing: { value: "0", unit: "normal" },
      lineHeight: { value: "0", unit: "normal" },
      marginBottom: { value: "0", unit: "px" },
      marginLeft: { value: "0", unit: "px" },
      marginRight: { value: "0", unit: "px" },
      marginTop: { value: "0", unit: "px" },
      paddingBottom: { value: "0", unit: "px" },
      paddingLeft: { value: "0", unit: "px" },
      paddingRight: { value: "0", unit: "px" },
      paddingTop: { value: "0", unit: "px" },
      textAlign: "left",
      textDecoration: "none",
      textTransform: "capitalize",
      zIndex: "auto",
    },
    text: "this is heading",
  },
  IMAGE: {
    imageAlignment: "left",
    linkTo: "",
    style: {
      backgroundColor: { r: 255, g: 255, b: 255, a: 1 },
      backgroundImage:
        "url('https://alppetro.co.id/dist/assets/images/default.jpg')",
      backgroundPosition: "left top",
      backgroundRepeat: "repeat",
      backgroundSize: "auto",
      borderBottomLeftRadius: { value: "0", unit: "px" },
      borderBottomRightRadius: { value: "0", unit: "px" },
      borderBottomWidth: { value: "0", unit: "px" },
      borderLeftWidth: { value: "0", unit: "px" },
      borderRightWidth: { value: "0", unit: "px" },
      borderStyle: "solid",
      borderTopLeftRadius: { value: "0", unit: "px" },
      borderTopRightRadius: { value: "0", unit: "px" },
      borderTopWidth: { value: "0", unit: "px" },
      boxShadowProps: {
        boxShadowBlur: { value: "0", unit: "px" },
        boxShadowColor: "black",
        boxShadowInset: "",
        boxShadowSpread: { value: "0", unit: "px" },
        boxShadowX: { value: "0", unit: "px" },
        boxShadowY: { value: "0", unit: "px" },
      },
      marginBottom: { value: "0", unit: "px" },
      marginLeft: { value: "0", unit: "px" },
      marginRight: { value: "0", unit: "px" },
      marginTop: { value: "0", unit: "px" },
      maxWidth: { value: "0", unit: "auto" },
      opacity: "1",
      paddingBottom: { value: "0", unit: "px" },
      paddingLeft: { value: "0", unit: "px" },
      paddingRight: { value: "0", unit: "px" },
      paddingTop: { value: "0", unit: "px" },
      width: { value: "0", unit: "auto" },
      zIndex: "auto",
    },
    text: "this is image",
  },
  INNERSECTION: {
    style: {
      alignItems: "stretch",
      backgroundColor: { r: 255, g: 255, b: 255, a: 1 },
      backgroundImage: "url('')",
      gap: { value: "16", unit: "px" },
      height: { value: "0", unit: "auto" },
      justifyContent: "space-evenly",
      marginBottom: { value: "0", unit: "px" },
      marginLeft: { value: "0", unit: "px" },
      marginRight: { value: "0", unit: "px" },
      marginTop: { value: "0", unit: "px" },
      maxWidth: { value: "0", unit: "auto" },
      minHeight: { value: "300", unit: "px" },
      overflow: "visible",
      paddingBottom: { value: "16", unit: "px" },
      paddingLeft: { value: "16", unit: "px" },
      paddingRight: { value: "16", unit: "px" },
      paddingTop: { value: "16", unit: "px" },
      width: { value: "0", unit: "auto" },
      zIndex: "auto",
    },
    text: "this is inner section",
  },
  INNERSECTION_LAYOUT: {
    style: {
      alignItems: "center",
      backgroundColor: { r: 255, g: 255, b: 255, a: 1 },
      gap: { value: "16", unit: "px" },
      height: { value: "0", unit: "auto" },
      justifyContent: "center",
      marginBottom: { value: "0", unit: "px" },
      marginLeft: { value: "0", unit: "px" },
      marginRight: { value: "0", unit: "px" },
      marginTop: { value: "0", unit: "px" },
      overflow: "visible",
      paddingBottom: { value: "0", unit: "px" },
      paddingLeft: { value: "0", unit: "px" },
      paddingRight: { value: "0", unit: "px" },
      paddingTop: { value: "0", unit: "px" },
      zIndex: "auto",
    },
    text: "this is inner section layout",
  },
  TEXT_EDITOR: {
    style: {
      backgroundColor: { r: 255, g: 255, b: 255, a: 1 },
      marginBottom: { value: "0", unit: "px" },
      marginLeft: { value: "0", unit: "px" },
      marginRight: { value: "0", unit: "px" },
      marginTop: { value: "0", unit: "px" },
      paddingBottom: { value: "0", unit: "px" },
      paddingLeft: { value: "0", unit: "px" },
      paddingRight: { value: "0", unit: "px" },
      paddingTop: { value: "0", unit: "px" },
      zIndex: "auto",
    },
    text: "this is text editor",
    textEditorValue: null,
    textEditorValueHTML: "",
  },
};
