export const PropsUnitOptions = {
  alignItems: ["center", "flex-end", "flex-start", "stretch"],
  backgroundPosition: [
    "center",
    "center bottom",
    "center top",
    "left",
    "left bottom",
    "left top",
    "right",
    "right bottom",
    "right top",
  ],
  backgroundRepeat: [
    "no-repeat",
    "repeat",
    "repeat-x",
    "repeat-y",
    "round",
    "space",
  ],
  backgroundSize: ["auto", "contain", "cover"],
  borderBottomLeftRadius: ["%", "em", "px", "rem"],
  borderBottomRightRadius: ["%", "em", "px", "rem"],
  borderBottomWidth: ["em", "px", "rem"],
  borderLeftWidth: ["em", "px", "rem"],
  borderRightWidth: ["em", "px", "rem"],
  borderStyle: ["dashed", "dotted", "none", "solid"],
  borderTopWidth: ["em", "px", "rem"],
  borderTopLeftRadius: ["%", "em", "px", "rem"],
  borderTopRightRadius: ["%", "em", "px", "rem"],
  boxShadowBlur: ["em", "px", "rem"],
  boxShadowInset: ["", "inset"],
  boxShadowSpread: ["em", "px", "rem"],
  boxShadowValue: ["em", "px", "rem"],
  boxShadowX: ["em", "px", "rem"],
  boxShadowY: ["em", "px", "rem"],
  fontSize: ["%", "em", "px", "rem"],
  fontWeight: ["bold", "normal"],
  gap: ["%", "em", "px", "rem"],
  height: ["auto", "%", "em", "px", "rem", "vh"],
  imageAlignment: ["center", "left", "right"],
  justifyContent: [
    "center",
    "flex-end",
    "flex-start",
    "space-around",
    "space-between",
    "space-evenly",
  ],
  letterSpacing: ["em", "normal", "px", "rem"],
  lineHeight: ["%", "em", "normal", "px", "rem"],
  marginBottom: ["auto", "%", "em", "px", "rem"],
  marginLeft: ["auto", "%", "em", "px", "rem"],
  marginRight: ["auto", "%", "em", "px", "rem"],
  marginTop: ["auto", "%", "em", "px", "rem"],
  maxHeight: ["auto", "%", "em", "px", "rem", "vh"],
  maxWidth: ["auto", "%", "em", "px", "rem", "vw"],
  minHeight: ["auto", "%", "em", "px", "rem", "vh"],
  minWidth: ["auto", "%", "em", "px", "rem", "vw"],
  overflow: ["auto", "hidden", "scroll", "visible"],
  paddingBottom: ["auto", "%", "em", "px", "rem"],
  paddingLeft: ["auto", "%", "em", "px", "rem"],
  paddingRight: ["auto", "%", "em", "px", "rem"],
  paddingTop: ["auto", "%", "em", "px", "rem"],
  textAlign: ["center", "justify", "left", "right"],
  textDecoration: [
    "line-through",
    "none",
    "overline",
    "underline",
    "underline overline",
  ],
  textTransform: ["capitalize", "lowercase", "none", "uppercase"],
  width: ["auto", "%", "em", "px", "rem", "vw"],
};
