export const PropsTypes = {
  ALIGN_ITEMS: "Align Items",
  COLOR: "Color",
  BACKGROUND_COLOR: "Background Color",
  BACKGROUND_IMAGE: "Background Image",
  BACKGROUND_POSITION: "Background Position",
  BACKGROUND_REPEAT: "Background Repeat",
  BACKGROUND_SIZE: "Background Size",
  BORDER_BOTTOM_LEFT_RADIUS: "Border Bottom Left Radius",
  BORDER_BOTTOM_RIGHT_RADIUS: "Border Bottom Right Radius",
  BORDER_BOTTOM_WIDTH: "Border Bottom Width",
  BORDER_COLOR: "Border Color",
  BORDER_LEFT_WIDTH: "Border Left Width",
  BORDER_RIGHT_WIDTH: "Border Right Width",
  BORDER_STYLE: "Border Style",
  BORDER_TOP_LEFT_RADIUS: "Border Top Left Radius",
  BORDER_TOP_RIGHT_RADIUS: "Border Top Right Radius",
  BORDER_TOP_WIDTH: "Border Top Width",
  BORDER_WEIGHT: "Border Weight",
  BOX_SHADOW_BLUR: "Box Shadow Blur",
  BOX_SHADOW_COLOR: "Box Shadow Color",
  BOX_SHADOW_INSET: "Box Shadow Inset",
  BOX_SHADOW_SPREAD: "Box Shadow Spread",
  BOX_SHADOW_X: "Box Shadow X",
  BOX_SHADOW_Y: "Box Shadow Y",
  BUTTON_ALIGNMENT: "Button Alignment",
  CONTROLS: "Controls",
  DIVIDER_TEXT: "Divider Text",
  FONT_SIZE: "Font Size",
  FONT_WEIGHT: "Font Weight",
  GAP: "Gap",
  HEIGHT: "Height",
  ICON: "Icon",
  IMAGE_ALIGNMENT: "Image Alignment",
  IMAGE_GALLERY_ALIGNMENT: "Image Gallery Alignment",
  IMAGE_GALLERY_IMAGES: "Image Gallery Images",
  INFINITE: "Infinite",
  INNER_SECTION_LAYOUT: "Inner Section Layout",
  JUSTIFY_CONTENT: "Justify Content",
  LETTER_SPACING: "Letter Spacing",
  LINE_HEIGHT: "Line Height",
  LINK_TO: "Link To",
  LOCATION: "Set Location",
  LOOP: "Loop",
  MARGIN_BOTTOM: "Margin Bottom",
  MARGIN_LEFT: "Margin Left",
  MARGIN_RIGHT: "Margin Right",
  MARGIN_TOP: "Margin Top",
  MAX_WIDTH: "Max Width",
  MIN_HEIGHT: "Min Height",
  MUTED: "Muted",
  OPACITY: "Opacity",
  OVERFLOW: "Overflow",
  PADDING_BOTTOM: "Padding Bottom",
  PADDING_LEFT: "Padding Left",
  PADDING_RIGHT: "Padding Right",
  PADDING_TOP: "Padding Top",
  PLAYING: "Auto Play",
  SHOW_BULLETS: "Show Bullets",
  SHOW_FULLSCREEN_BUTTON: "Show Fullscreen Button",
  SHOW_NAV: "Show Nav",
  SHOW_PLAY_BUTTON: "Show Play Button",
  SHOW_THUMBNAILS: "Show Thumbnails",
  SLIDE_INTERVAL: "Slide Interval",
  SOURCE: "Source",
  STAR_RATING_CAP: "Star Rating Cap",
  STAR_RATING_VALUE: "Star Rating Value",
  TEXT: "Text",
  TEXT_ALIGN: "Text Align",
  TEXT_DECORATION: "Text Decoration",
  TEXT_EDITOR_VALUE: "Text Editor Value",
  TEXT_TRANSFORM: "Text Transform",
  THUMBNAIL_POSITION: "Thumbnail Position",
  USER_NAVBAR_LOGO: "User Navbar Logo",
  USER_NAVBAR_LOGO_IS_SHOW: "User Navbar Logo Is Show",
  USER_NAVBAR_LOGO_MAX_HEIGHT: "User Navbar Logo Max Height",
  USER_NAVBAR_LOGO_MAX_WIDTH: "User Navbar Logo Max Width",
  USER_NAVBAR_MENU: "User Navbar Menu",
  USER_NAVBAR_MENU_COLOR: "User Navbar Menu Color",
  USER_NAVBAR_SUBMENU: "User Navbar Submenu",
  USER_NAVBAR_SUBMENU_BACKGROUND_COLOR: "User Navbar Submenu Background Color",
  USER_NAVBAR_SUBMENU_COLOR: "User Navbar Submenu Color",
  USER_NAVBAR_SUBMENU_FONT_SIZE: "User Navbar Submenu Font Size",
  USER_NAVBAR_SUBMENU_FONT_WEIGHT: "User Navbar Submenu Font Weight",
  USER_NAVBAR_SUBMENU_GAP: "User Navbar Submenu Gap",
  USER_NAVBAR_SUBMENU_TEXT_TRANSFORM: "User Navbar Submenu Text Transform",
  WIDTH: "Width",
  ZINDEX: "Z - Index",
};
