export const PropsTypes = {
  ALIGN_ITEMS: "Align Items",
  COLOR: "Color",
  BACKGROUND_COLOR: "Background Color",
  BACKGROUND_IMAGE: "Background Image",
  BACKGROUND_POSITION: "Background Position",
  BACKGROUND_REPEAT: "Background Repeat",
  BACKGROUND_SIZE: "Background Size",
  BORDER_BOTTOM_LEFT_RADIUS: "Border Bottom Left Radius",
  BORDER_BOTTOM_RIGHT_RADIUS: "Border Bottom Right Radius",
  BORDER_BOTTOM_WIDTH: "Border Bottom Width",
  BORDER_COLOR: "Border Color",
  BORDER_LEFT_WIDTH: "Border Left Width",
  BORDER_RIGHT_WIDTH: "Border Right Width",
  BORDER_STYLE: "Border Style",
  BORDER_TOP_LEFT_RADIUS: "Border Top Left Radius",
  BORDER_TOP_RIGHT_RADIUS: "Border Top Right Radius",
  BORDER_TOP_WIDTH: "Border Top Width",
  BOX_SHADOW_BLUR: "Box Shadow Blur",
  BOX_SHADOW_COLOR: "Box Shadow Color",
  BOX_SHADOW_INSET: "Box Shadow Inset",
  BOX_SHADOW_SPREAD: "Box Shadow Spread",
  BOX_SHADOW_X: "Box Shadow X",
  BOX_SHADOW_Y: "Box Shadow Y",
  CONTROLS: "Controls",
  FONT_SIZE: "Font Size",
  FONT_WEIGHT: "Font Weight",
  GAP: "Gap",
  HEIGHT: "Height",
  IMAGE_ALIGNMENT: "Image Alignment",
  INNER_SECTION_LAYOUT: "Inner Section Layout",
  JUSTIFY_CONTENT: "Justify Content",
  LETTER_SPACING: "Letter Spacing",
  LINE_HEIGHT: "Line Height",
  LINK_TO: "Link To",
  LOCATION: "Location",
  LOOP: "Loop",
  MARGIN_BOTTOM: "Margin Bottom",
  MARGIN_LEFT: "Margin Left",
  MARGIN_RIGHT: "Margin Right",
  MARGIN_TOP: "Margin Top",
  MAX_WIDTH: "Max Width",
  MIN_HEIGHT: "Min Height",
  MUTED: "Muted",
  OPACITY: "Opacity",
  OVERFLOW: "Overflow",
  PADDING_BOTTOM: "Padding Bottom",
  PADDING_LEFT: "Padding Left",
  PADDING_RIGHT: "Padding Right",
  PADDING_TOP: "Padding Top",
  PLAYING: "Auto Play",
  SOURCE: "Source",
  TEXT: "Text",
  TEXT_ALIGN: "Text Align",
  TEXT_DECORATION: "Text Decoration",
  TEXT_EDITOR_VALUE: "Text Editor Value",
  TEXT_TRANSFORM: "Text Transform",
  WIDTH: "Width",
  ZINDEX: "Z - Index",
};
