export const ItemTypes = {
  BOARD: "Board",
  BUTTON: "Button",
  CHOOSE_PAGE_BUTTON: "Choose Page Button",
  COMPONENT_LIST_BUTTON: "Component List Button",
  DOM_TREE_BUTTON: "DOM Tree Button",
  DOM_TREE_ELEMENT: "DOM Tree Element",
  DIVIDER: "Divider",
  HEADING: "Heading",
  ICON: "Icon",
  IMAGE: "Image",
  IMAGE_GALLERY: "Image Gallery",
  INNERSECTION: "Inner Section",
  INNERSECTION_LAYOUT: "Inner Section Layout",
  MAP_COMPONENT: "Map Component",
  SPACER: "Spacer",
  STAR_RATING: "Star Rating",
  TEXT_EDITOR: "Text Editor",
  USER_NAVBAR: "User Navbar",
  USER_NAVBAR_MENU: "User Navbar Menu",
  USER_NAVBAR_SUBMENU: "User Navbar Sub Menu",
  USER_FOOTER: "User Footer",
  VIDEO: "Video",
};
